spring:
  application:
    name: NEPM

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:mysql://nepmdev.binbow.link:3396/nepm?useUnicode=true&characterEncoding=utf-8
    username: dev
    password: NEPM@Dev@2021
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10

  data:
    redis:
      key:
        prefix:
          authCode: "portal:authCode:"  # 验证码的键前缀，用于组织和标识验证码相关的键
          orderId: "portal:orderId:"    # 订单ID的键前缀，用于组织和标识订单ID相关的键
        expire:
          authCode: 60 # 验证码的过期时间，单位是秒
      host: nepmdev.binbow.link
      port: 6369
      password: NEPM@Password@123456
      timeout: 10000
      connectTimeout: 5000
      lettuce:
        pool:
          min-idle: 5
          max-idle: 10
          max-active: 100
          max-wait: 2000




mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: true
  global-config:
    # 全局配置
    db-config:
      # 数据库配置
      id-type: auto

minio:
  endpoint: http://123.57.210.112:9001
  accessKey: MGZM
  secretKey: MGZm123456